### ISSUE TITLE
Session based tracking of attendance

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#721]
Sessiongenaue Erfassung der Anwesenheit (auf report.php kann jede Session einzeln bearbeitet werden)
Sessiongenaue Auswertung der Anwesenheiten (Bei 10 Sessions und 10 Anmeldungen kann z.b. der counter auf 75 stehen)

- [x] Table reload mit cache purge bei Präsenzstatus-Änderung
- [x] Anmerkung im selben Form mitspeichern
- [x] Strings richtig auflösen (via wbtable?)
- [x] Counter auf Option-Ebene implementieren

dafür die Report2 Arbeiten
#672 
#674 
#673 
#675 
#676 
#677
